apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  labels:
    app.kubernetes.io/name: mailhog
    app.kubernetes.io/part-of: oficina
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mailhog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mailhog
        app.kubernetes.io/part-of: oficina
    spec:
      containers:
        - name: mailhog
          image: mailhog/mailhog:v1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1025
              name: smtp
            - containerPort: 8025
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
  labels:
    app.kubernetes.io/name: mailhog
    app.kubernetes.io/part-of: oficina
spec:
  selector:
    app.kubernetes.io/name: mailhog
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: http
      port: 8025
      targetPort: 8025
  type: ClusterIP
