#!/usr/bin/env bash

if [[ -n "${OFICINA_SCRIPT_DEFAULTS_SH_LOADED:-}" ]]; then
  return 0 2>/dev/null || exit 0
fi

OFICINA_SCRIPT_DEFAULTS_SH_LOADED=true

OFICINA_PROJECT_NAME="${OFICINA_PROJECT_NAME:-oficina}"
OFICINA_ENVIRONMENT_NAME="${OFICINA_ENVIRONMENT_NAME:-${OFICINA_ENVIRONMENT:-lab}}"
OFICINA_ENVIRONMENT="${OFICINA_ENVIRONMENT:-${OFICINA_ENVIRONMENT_NAME}}"
OFICINA_SECRET_PREFIX="${OFICINA_SECRET_PREFIX:-${OFICINA_PROJECT_NAME}/${OFICINA_ENVIRONMENT_NAME}}"

OFICINA_APP_NAME="${OFICINA_APP_NAME:-oficina-app}"
OFICINA_AUTH_LAMBDA_NAME="${OFICINA_AUTH_LAMBDA_NAME:-oficina-auth-lambda}"
OFICINA_NOTIFICACAO_LAMBDA_NAME="${OFICINA_NOTIFICACAO_LAMBDA_NAME:-oficina-notificacao-lambda}"

OFICINA_TERRAFORM_ENV_DIR="${OFICINA_TERRAFORM_ENV_DIR:-${REPO_ROOT:-}/terraform/environments/${OFICINA_ENVIRONMENT_NAME}}"
OFICINA_TF_STATE_KEY="${OFICINA_TF_STATE_KEY:-${OFICINA_SECRET_PREFIX}/terraform.tfstate}"

OFICINA_EKS_CLUSTER_NAME="${OFICINA_EKS_CLUSTER_NAME:-eks-${OFICINA_ENVIRONMENT_NAME}}"
OFICINA_DB_IDENTIFIER="${OFICINA_DB_IDENTIFIER:-${OFICINA_PROJECT_NAME}-postgres-${OFICINA_ENVIRONMENT_NAME}}"
OFICINA_DB_K8S_SECRET_NAME="${OFICINA_DB_K8S_SECRET_NAME:-${OFICINA_PROJECT_NAME}-database-env}"
OFICINA_JWT_K8S_SECRET_NAME="${OFICINA_JWT_K8S_SECRET_NAME:-${OFICINA_PROJECT_NAME}-jwt-keys}"

OFICINA_DB_APP_SECRET_ID="${OFICINA_DB_APP_SECRET_ID:-${OFICINA_SECRET_PREFIX}/database/app}"
OFICINA_AUTH_DB_SECRET_ID="${OFICINA_AUTH_DB_SECRET_ID:-${OFICINA_SECRET_PREFIX}/database/auth-lambda}"
OFICINA_JWT_SECRET_ID="${OFICINA_JWT_SECRET_ID:-${OFICINA_SECRET_PREFIX}/jwt}"

OFICINA_AUTH_LAMBDA_FUNCTION_NAME="${OFICINA_AUTH_LAMBDA_FUNCTION_NAME:-${OFICINA_AUTH_LAMBDA_NAME}-${OFICINA_ENVIRONMENT_NAME}}"
OFICINA_NOTIFICACAO_LAMBDA_FUNCTION_NAME="${OFICINA_NOTIFICACAO_LAMBDA_FUNCTION_NAME:-${OFICINA_NOTIFICACAO_LAMBDA_NAME}-${OFICINA_ENVIRONMENT_NAME}}"
OFICINA_AUTH_LAMBDA_ARTIFACT_PREFIX="${OFICINA_AUTH_LAMBDA_ARTIFACT_PREFIX:-${OFICINA_SECRET_PREFIX}/lambda/${OFICINA_AUTH_LAMBDA_NAME}}"
OFICINA_NOTIFICACAO_LAMBDA_ARTIFACT_PREFIX="${OFICINA_NOTIFICACAO_LAMBDA_ARTIFACT_PREFIX:-${OFICINA_SECRET_PREFIX}/lambda/${OFICINA_NOTIFICACAO_LAMBDA_NAME}}"

OFICINA_OBSERVABILITY_APP_LOG_GROUP_NAME="${OFICINA_OBSERVABILITY_APP_LOG_GROUP_NAME:-/${OFICINA_PROJECT_NAME}/${OFICINA_ENVIRONMENT_NAME}/eks/${OFICINA_APP_NAME}}"
OFICINA_PLATFORM_OVERLAY_DIR="${OFICINA_PLATFORM_OVERLAY_DIR:-k8s/overlays/${OFICINA_ENVIRONMENT_NAME}-platform}"
OFICINA_APP_OVERLAY_DIR="${OFICINA_APP_OVERLAY_DIR:-k8s/overlays/${OFICINA_ENVIRONMENT_NAME}-app}"
