apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-app-config
  labels:
    app.kubernetes.io/name: oficina-app
    app.kubernetes.io/part-of: oficina
data:
  JAVA_TOOL_OPTIONS: -Dquarkus.hibernate-orm.schema-management.strategy=update
  OFICINA_AUTH_ISSUER: OFICINA_AUTH_ISSUER_PLACEHOLDER
  OFICINA_AUTH_AUDIENCE: oficina-app
  MP_JWT_VERIFY_PUBLICKEY_LOCATION: OFICINA_AUTH_JWKS_URI_PLACEHOLDER
  OTEL_SERVICE_NAME: oficina-app
  OTEL_RESOURCE_ATTRIBUTES: service.namespace=oficina,deployment.environment=lab
  OTEL_EXPORTER_OTLP_ENDPOINT: ""
  OTEL_EXPORTER_OTLP_PROTOCOL: grpc
  OTEL_TRACES_EXPORTER: none
  OTEL_METRICS_EXPORTER: none
  OTEL_LOGS_EXPORTER: none
  OFICINA_OBSERVABILITY_ENABLED: "true"
  OFICINA_OBSERVABILITY_JSON_LOGS_ENABLED: "true"
  OFICINA_OBSERVABILITY_METRICS_ENABLED: "true"
  OFICINA_OBSERVABILITY_TRACING_ENABLED: "true"
  DEPLOYMENT_ENVIRONMENT: lab
  QUARKUS_DATASOURCE_REACTIVE_POSTGRESQL_SSL_MODE: require
  QUARKUS_DATASOURCE_REACTIVE_TRUST_ALL: "true"
  QUARKUS_MAILER_HOST: mailhog
  QUARKUS_MAILER_PORT: "1025"
  QUARKUS_MAILER_TLS: "false"
  QUARKUS_MAILER_START_TLS: DISABLED
  QUARKUS_MAILER_MOCK: "false"
  QUARKUS_MAILER_FROM: noreply@oficina.local
